Repository Learning-Is-Vital-In-Development/23-13-DesignPattern, pull requests merged in 2023-09, with the labels that each got.

#56 [9, 10, 11주차] 9, 10, 11. 반복자 & 컴포넌트 패턴, 상태 패턴, 프록시 패턴 - 배정연
  ch09/배정연/jungyeon.md
  ch10/배정연/jungyeon.md
  ch11/배정연/jungyeon.md
Labels: size/L

#55 [9, 10, 11주차] 9, 10, 11. 반복자 & 컴포넌트 패턴, 상태 패턴, 프록시 패턴 - 박우람
  ch09/박우람/README.md
  ch10/박우람/README.md
  ch10/박우람/img/상태패턴.png
  ch11/박우람/README.md
Labels: size/L

#53 [10, 11주차] 10, 11. 상태 패턴, 프록시 패턴 - 홍성주
  ch10/홍성주/state/ChargeState.java
  ch10/홍성주/state/CoinRepository.java
  ch10/홍성주/state/CoinState.java
  ch10/홍성주/state/NoCoinState.java
  ch10/홍성주/state/SoldState.java
  ch10/홍성주/state/State.java
  ch10/홍성주/state/TicketMachine.java
  ch10/홍성주/state/TicketPractice.java
  ch10/홍성주/state/TicketPrinter.java
  ch10/홍성주/홍성주.md
  ch11/홍성주/proxy/RealSubject.java
  ch11/홍성주/proxy/Subject.java
  ch11/홍성주/proxy/basic/ProxySubject.java
  ch11/홍성주/proxy/virtual/VirtualProxySubject.java
  ch11/홍성주/홍성주.md
Labels: size/XL

#54 [10주차] 10. 상태 패턴 프록시패턴 - 김정민
  ch10/김정민/image-1.png
  ch10/김정민/상태패턴.md
  ch11/김정민/image-1.png
  ch11/김정민/프록시패턴.md
Labels: size/M

#57 [11주차] 12,13,14. 복합 패턴&실전 디자인 패턴&기타 패턴 - 심규민
  ch12/심규민/심규민.md
  ch13/심규민/심규민.md
  ch14/심규민/img/BridgePattern.png
  ch14/심규민/img/BuilderPattern.png
  ch14/심규민/img/ChainOfResponsibilityPattern.png
  ch14/심규민/img/FlyWeightPattern.png
  ch14/심규민/img/InterpreterPattern.svg
  ch14/심규민/img/MediatorPattern.png
  ch14/심규민/img/MementoPattern.png
  ch14/심규민/img/PrototypePattern.png
  ch14/심규민/img/VisitorPattern.png
  ch14/심규민/심규민.md
Labels: size/L

#58 [11주차] 12,13,14. 복합 패턴&실전 디자인 패턴&기타 패턴 - 박우람
  ch12/박우람/박우람.md
  ch13/박우람/박우람.md
  ch14/박우람/박우람.md
Labels: size/L
